### ISSUE TITLE
Explicitly choose if milestones are referenced by title or id

### ISSUE THREAD

**Issue by khmarbaise** [spring-io/github-changelog-generator#41]
I have tested the application on plain command line first:
```
~/tools/jdk-11.0.7+10/Contents/Home/bin/java -jar target/github-release-notes-generator.jar 51 release-mojo-parent.md 
```
The used milestone: https://github.com/mojohaus/mojo-parent/milestone/9?closed=1

I have ran via command line different other repositories without any issue.

I have created a configuration file `application.yml` like this:
```yaml
releasenotes:
  github:
    organization: mojohaus
    repository: mojo-parent
    username: khmarbaise
    password:xxxxx
```
which unfortunately failed with this:
```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.5.RELEASE)

2020-05-29 23:01:31.750  INFO 20357 --- [           main] io.spring.releasenotes.Application       : Starting Application v0.0.3-SNAPSHOT on khmac.local with PID 20357 (/Users/khmarbaise/ws-git-github/github-release-notes-generator/target/github-release-notes-generator.jar started by khmarbaise in /Users/khmarbaise/ws-git-github/github-release-notes-generator)
2020-05-29 23:01:31.753  INFO 20357 --- [           main] io.spring.releasenotes.Application       : No active profile set, falling back to default profiles: default
2020-05-29 23:01:32.361  INFO 20357 --- [           main] io.spring.releasenotes.Application       : Started Application in 1.401 seconds (JVM running for 1.942)
2020-05-29 23:01:33.015  INFO 20357 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-05-29 23:01:33.020 ERROR 20357 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:778) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at io.spring.releasenotes.Application.main(Application.java:35) ~[classes!/:0.0.3-SNAPSHOT]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[github-release-notes-generator.jar:0.0.3-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[github-release-notes-generator.jar:0.0.3-SNAPSHOT]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[github-release-notes-generator.jar:0.0.3-SNAPSHOT]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[github-release-notes-generator.jar:0.0.3-SNAPSHOT]
Caused by: org.springframework.web.client.HttpClientErrorException$UnprocessableEntity: 422 Unprocessable Entity: [{"message":"Validation Failed","errors":[{"value":"51","resource":"Issue","field":"milestone","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/issues/#list-issues"}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:141) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:112) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.web.client.RestTemplate.getForEntity(RestTemplate.java:342) ~[spring-web-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at io.spring.releasenotes.github.service.GithubService.getPage(GithubService.java:94) ~[classes!/:0.0.3-SNAPSHOT]
	at io.spring.releasenotes.github.service.GithubService.getAll(GithubService.java:82) ~[classes!/:0.0.3-SNAPSHOT]
	at io.spring.releasenotes.github.service.GithubService.getIssuesForMilestone(GithubService.java:77) ~[classes!/:0.0.3-SNAPSHOT]
	at io.spring.releasenotes.generator.ReleaseNotesGenerator.generate(ReleaseNotesGenerator.java:75) ~[classes!/:0.0.3-SNAPSHOT]
	at io.spring.releasenotes.CommandProcessor.run(CommandProcessor.java:58) ~[classes!/:0.0.3-SNAPSHOT]
	at io.spring.releasenotes.CommandProcessor.run(CommandProcessor.java:52) ~[classes!/:0.0.3-SNAPSHOT]
	at io.spring.releasenotes.CommandProcessor.run(CommandProcessor.java:46) ~[classes!/:0.0.3-SNAPSHOT]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	... 13 common frames omitted
```

**Comment by khmarbaise** [comment]
So after diving more into that I I've found the problem.
The problem is located based https://github.com/spring-io/github-release-notes-generator/blob/master/src/main/java/io/spring/releasenotes/generator/ReleaseNotesGenerator.java#L80
```java
	private int getMilestoneNumber(String milestone) {
		try {
			return Integer.parseInt(milestone);
		}
		catch (NumberFormatException ex) {
			return this.service.getMilestoneNumber(milestone, this.organization, this.repository);
		}
	}
```
If I just use the line as 
```
return this.service.getMilestoneNumber(milestone, this.organization, this.repository);
```
In the method `getMilestoneNumber`. This will result in working without any exception.

**Comment by wilkinsona** [comment]
The generator supports specifying the milestone as either a name or as a number, with anything that can be parsed as an integer assumed to be a milestone number. For what was named `60` and is now named `mojo-parent-60`, you could have used `9` as that is its number: https://github.com/mojohaus/mojo-parent/milestone/9.

I think this is the first time that the generator's been used with a project that has a milestone name that can be parsed as a number. To support names that look like numbers while also continuing to support identifying the milestone via its number, I think we'd need to introduce a new option so that the generate knows how the identifier should be treated. Alternatively, we could drop support for identifying a milestone by its number. For our own usage at least, I think we largely identify the milestone by name now.

**Comment by wilkinsona** [comment]
Relates to https://github.com/spring-io/github-release-notes-generator/issues/19 which added name support.

**Comment by khmarbaise** [comment]
@wilkinsona I already thought that this was the intention nevertheless thanks for the explanation. I think the best option would be to support via name.
